### ISSUE TITLE
a crash on "cv::ximgproc::findEllipses" 

### ISSUE THREAD

**Issue by jinneigeyu** [opencv/opencv_contrib#3525]
##### System information (version)

- OpenCV =>4.7.0 & 4.8 
- Operating System / Platform => windows x64 x86
- Compiler => vs2019

##### Issue submission checklist

 - [ *] I report the issue, it's not a question
   
 - [ ] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
   
 - [ *] I updated to the latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc
   

at line 1305 of  \modules\ximgproc\src\find_ellipses.cpp [https://github.com/opencv/opencv_contrib/blob/4f66f8677b19766ed6c25d46f40d545842a7fafd/modules/ximgproc/src/find_ellipses.cpp#L1305](url)
![Snipaste_2023-07-12_10-55-54](https://github.com/opencv/opencv_contrib/assets/51145178/3ca65b21-1af1-41e3-b49f-170cd1c06f22)

**Comment by bobby1125** [comment]
I met the same problem. And I find that this bug occurs only in the debug mode and is fine in the release mode. Is there any suggestions?

**Comment by sturkmen72** [comment]
probably solved by #3515 this issue can be closed down.

**Comment by dmaritex** [comment]
> I met the same problem. And I find that this bug occurs only in the debug mode and is fine in the release mode. Is there any suggestions?

Me too, using openCV 4.11 and it seems the bug is still there. In debug mode it crashes on the first image, in release it crashes after a little while but somewhere else, while labelling ellipses.
Re-opened the issue #4022
